[phases.setup]
nixPkgs = ['php83', 'nodejs-22_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = ['php artisan config:cache', 'php artisan route:cache']

[start]
cmd = 'php artisan migrate --force && php artisan storage:link && php -S 0.0.0.0:$PORT -t public'